title: Marco Labarile
description: My Personal Website
about: Software enthusiast
author: Marco Labarile

logo: /static/img/avatar.png

github: https://github.com/labarilem/

baseurl: ""
url: ""

allowsearch: true

google_analytics: UA-117745201-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: [npm]

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
